// Code generated by protoc-gen-cobra.
// source: vpe.api.proto
// DO NOT EDIT!

package fdio

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
